###################################
# Airflow - Common Configs
###################################
airflow:
  executor: CeleryExecutor

###################################
# Airflow - Worker Configs
###################################
workers:
  ## resource requests/limits for the airflow worker Pods
  ##
  ## EXAMPLE:
  ##   resources:
  ##     requests:
  ##       cpu: "1000m"
  ##       memory: "2Gi"
  ##
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "100m"
      memory: "2Gi"

###################################
# Airflow - DAGs Configs
###################################
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client
    # access mode of the persistent volume
    accessMode: ReadWriteMany

  gitSync:
    enabled: true

    # git repo clone url
    # ssh examples ssh://git@github.com/apache/airflow.git
    # git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/ivanovishado/WizeDataEngCapstoneProj
    branch: third-deliverable
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"

###################################
# Airflow - Logs Configs
###################################
logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client

secret:
  - envName: "AIRFLOW_CONN_POSTGRES_DEFAULT"
    secretName: "postgres-conn"
    secretKey: "AIRFLOW_CONN_POSTGRES_DEFAULT"
  - envName: "AIRFLOW_CONN_AWS_DEFAULT"
    secretName: "aws-conn"
    secretKey: "AIRFLOW_CONN_AWS_DEFAULT"
  - envName: "AIRFLOW_CONN_EMR_DEFAULT"
    secretName: "emr-conn"
    secretKey: "AIRFLOW_CONN_EMR_DEFAULT"
